#!/usr/bin/env python3
"""
Regenerate `benchmarks/runs/INDEX.md` by scanning `benchmarks/runs/<version>/manifest.json`.

Each release snapshot directory is expected to look like:

    benchmarks/runs/v0.1.1/
        manifest.json     # {"version": "v0.1.1", "git_sha": "...", "date": "...", ...}
        <suite>.json      # one schema-v2 file per suite
        summary.md        # human-readable table

This script reads every `manifest.json` it finds, validates the keys it relies on, and
rewrites the table at the bottom of `benchmarks/runs/INDEX.md` (everything below the
"## Index" header). The header / explanatory text above the table is preserved as-is.

Usage:
    python3 scripts/bench/regen_index.py
    python3 scripts/bench/regen_index.py --check    # exit 1 if INDEX.md is stale

CI runs this in `--check` mode on every PR (P2 wiring) so reviewers cannot land a snapshot
without also bumping the index.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]
RUNS_DIR = REPO_ROOT / "benchmarks" / "runs"
INDEX_PATH = RUNS_DIR / "INDEX.md"


HEADER_BOUNDARY = "## Index"


def discover_manifests() -> List[Tuple[str, Dict]]:
    out: List[Tuple[str, Dict]] = []
    if not RUNS_DIR.is_dir():
        return out
    for child in sorted(RUNS_DIR.iterdir()):
        if not child.is_dir():
            continue
        manifest = child / "manifest.json"
        if not manifest.exists():
            continue
        try:
            doc = json.loads(manifest.read_text())
        except Exception as e:
            print(f"WARN: skipping {manifest}: {e}", file=sys.stderr)
            continue
        out.append((child.name, doc))
    return out


def render_row(version_dir: str, doc: Dict) -> str:
    version = str(doc.get("version", version_dir))
    date = str(doc.get("date", "?"))
    hardware = str(doc.get("hardware", "?"))
    suites = doc.get("suites", [])
    if isinstance(suites, list):
        suites_str = ", ".join(str(s) for s in suites) or "?"
    else:
        suites_str = str(suites)
    notes = str(doc.get("notes", ""))
    return f"| {version} | {date} | {hardware} | {suites_str} | {notes} |"


def render_table(rows: List[str]) -> str:
    head = "| Version | Date | Hardware | Suites | Notes |\n|---|---|---|---|---|"
    if not rows:
        return head + "\n| _none yet_ | | | | First snapshot will be added with the next tagged release. |"
    return head + "\n" + "\n".join(rows)


def split_existing_index() -> Tuple[str, str]:
    """Return (header_block_inclusive_of_boundary, table_block) from the current file."""
    if not INDEX_PATH.exists():
        # Default header if file is missing.
        header = (
            "# Per-release benchmark snapshots\n\n"
            "Auto-generated by `scripts/bench/regen_index.py`. Do not edit by hand below the\n"
            "`## Index` line; edit per-snapshot `manifest.json` files instead.\n\n"
            "## Index\n"
        )
        return header, ""
    text = INDEX_PATH.read_text()
    idx = text.find(HEADER_BOUNDARY)
    if idx < 0:
        return text.rstrip() + "\n\n## Index\n", ""
    end = text.find("\n", idx) + 1
    return text[:end], text[end:]


def regenerate() -> str:
    header, _ = split_existing_index()
    rows = [render_row(name, doc) for name, doc in discover_manifests()]
    return header.rstrip("\n") + "\n\n" + render_table(rows) + "\n"


def main(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Don't write; exit 1 if INDEX.md would change.",
    )
    args = ap.parse_args(argv[1:])

    new_text = regenerate()
    current = INDEX_PATH.read_text() if INDEX_PATH.exists() else ""
    if args.check:
        if current.strip() == new_text.strip():
            print(f"OK: {INDEX_PATH.relative_to(REPO_ROOT)} is up to date")
            return 0
        print(
            f"FAIL: {INDEX_PATH.relative_to(REPO_ROOT)} is stale; "
            "run `python3 scripts/bench/regen_index.py` and commit the diff",
            file=sys.stderr,
        )
        return 1

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(new_text)
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
